CREATE TABLE IF NOT EXISTS user(ID INTEGER PRIMARY KEY, username TEXT, email TEXT, password TEXT)
CREATE TABLE IF NOT EXISTS ArtistMonitor(ID INTEGER PRIMARY KEY, DJName TEXT)
CREATE TABLE IF NOT EXISTS Tracks(Artist TEXT, Song TEXT, Label TEXT, Price TEXT, ChartPosition TEXT, Genre TEXT, Websource TEXT)